RPG/RPG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/',include('game.urls')),
    path('',include('log.urls')),


]

RPG/game/urls.py
from . import views
from django.urls import path

app_name='game'
urlpatterns = [
    path('base/',views.index, name='index'),
    path('charcter/',views.char_view, name='char'),
    path('kampf/',views.kampf_view, name='kampf'),
    path('charChreate/', views.charChreate_view, name='charChreate'),
    path('sieg/', views.sieg_view, name='sieg'),
    path('niederlage/', views.niederlage_view, name='niederlage'),


]

RPG/log/urls.py
from . import views
from django.urls import path


app_name='log'
urlpatterns = [
    path('',views.index, name='index'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

RPG/game/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls.base import *
from django.conf import settings
# Create your models here.
class CharMod(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    charName = models.CharField(max_length=50)
    charClasse = models.CharField(max_length=50)
    charATK = models.IntegerField(null=True)
    charDEF = models.IntegerField(null=True)
    charMAN = models.IntegerField(null=True)
    charEP = models.IntegerField(null=True)
    charLevel= models.IntegerField(null=True)
    besigtegegner= models.IntegerField(null=True)
    charLeben = models.IntegerField(null=True)

class EnemyMod(models.Model):
    id = models.IntegerField(primary_key = True)
    enemyName = models.CharField(max_length=50)
    enemyATK = models.IntegerField(null=True)
    enemyDEF = models.IntegerField(null=True)
    enemyMAN = models.IntegerField(null=True)
    enemyLeben = models.IntegerField(null=True)
    enemyBild = models.ImageField(),

RPG/game/forms.py
from django import forms
from django.contrib.auth.models import *
from .models import *
from django.forms.models import *
from django.forms import *


class charMaker(ModelForm):
    CHOICES = (("Krieger", "Krieger"), ("Magier", "Magier") )
    charClasse = ChoiceField(choices=CHOICES)

    class Meta:
        model = CharMod
        fields = ('charName', 'charClasse')
        labels = {
            'charName': 'Name deines Avatas',
            'charClasse': 'Classe deines Avatas',

        }

RPG/game/views.py
from django.shortcuts import *
from django.contrib.auth.forms import *
from django.contrib.auth import *
from django.urls.base import *
from .models import *
from .forms import *
from django.contrib.auth.models import *
from .gegner import *
from .ankreifer import *
import random

def index(request):
    user = get_object_or_404(User, username=request.user.username)
    return render(request, 'game/base.html', {'user':user})

def char_view(request):
    user = get_object_or_404(User, username=request.user.username)
    chars = CharMod.objects.filter(user = user)
    return render(request, 'game/charcter.html', {'chars': chars, 'user':user})

def kampf_view(request):
    if request.user.is_authenticated:
        gegner = Gegner()
    user = get_object_or_404(User, username=request.user.username)
    chars = CharMod.objects.filter(user=user)
    spieler = CharMod.objects.get(user=request.user)
    level = 1
    for i in chars:
        if i.user == request.user:
            ankreifer = Ankreifer() #damit die Werte des Chars suaber übergeben werden können
            ankreifer.level = i.charLevel
            ankreifer.atk = i.charATK
            ankreifer.man= i.charMAN
            ankreifer.dEF = i.charDEF
            ankreifer.leben = i.charLeben
            level = i.charLevel

    if level < 2:
        enemy = EnemyMod.objects.filter(id =1)
        for j in enemy:
            if j.id == 1:
                gegner.name = j.enemyName
                gegner.atk = j.enemyATK
                gegner.man = j.enemyMAN
                gegner.dEF = j.enemyDEF
                gegner.leben = j.enemyLeben
    else:
        idwahl = random.randrange(1,3)
        enemy = EnemyMod.objects.filter(id=idwahl)
        for k in enemy:
            gegner.name = k.enemyName
            gegner.atk = k.enemyATK
            gegner.man = k.enemyMAN
            gegner.dEF = k.enemyDEF
            gegner.leben = k.enemyLeben

        
    return render(request, 'game/kampf.html', {'gegner':gegner, 'chars': chars, 'user':user, 'ankreifer':ankreifer, 'spieler':spieler })

def charChreate_view(request):
    charMaker_form = charMaker()
    maker=charMaker_form.save(commit=False)
    if request.method == 'POST':
        charMaker_form = charMaker(request.POST)
        if charMaker_form.is_valid():
            maker=charMaker_form.save(commit=False)
            maker.user=request.user
            maker.charEP=0
            maker.charLevel=1
            maker.besigtegegner =0
            maker.charLeben = 50
            if maker.charClasse == 'Krieger':
                maker.charATK = 15
                maker.charDEF = 10
                maker.charMAN = 10
            elif maker.charClasse == 'Magier':
                maker.charATK = 10
                maker.charDEF = 10
                maker.charMAN = 15
            else:
                maker.charATK = 10
                maker.charDEF = 10
                maker.charMAN = 10
            maker.save()
            if maker:
                return redirect(reverse( 'game:char'))
    return render(request, 'game/charChreate.html', {'charMaker_form':charMaker_form, 'maker': maker})

def sieg_view (request):
    user = get_object_or_404(User, username=request.user.username)
    chars = CharMod.objects.filter(user=user)
    for i in chars:
        if i.user == request.user:
            i.besigtegegner += 1
            i.charEP += 10
            if i.charEP == 100:
                i.charLevel += 1
                #Level up
                if i.charClasse == 'Magier':
                    i.charMAN += 5
                    i.charDEF += 2
                    i.charATK += 2
                    i.charLeben += 5
                    i.charEP = 0
                else:
                    i.charMAN += 2
                    i.charDEF += 2
                    i.charATK += 5
                    i.charLeben += 5
                    i.charEP = 0

            i.save()
    return redirect(reverse('game:char'), {'user':user, 'chars':chars})

def niederlage_view(request):
    return redirect(reverse('game:char'))

RPG/game/templates/game/base.html
<!DOCTYPE html>
<html>
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" />
<script src="{% static 'forndend.js'%}"></script>
<head>
    <meta charset="UTF-8">
    <title>Game</title>
</head>
<body class = "kampf">
    {% block gameContent %}
    {% if request.user.is_authenticated %}
        <a href="{%url 'log:logout'%}">Logout</a>
        <h1>Dein Char</h1>
        <p>Hallo</p>
        <a href = "{%url 'game:char'%}"> Char</a>
    {%else%}
        <a href="{%url 'log:login'%}">Login</a>
        <a href="{%url 'log:register'%}">Account anlegen</a>

    {% endif %}

    {% endblock %}

</body>
<script type="text/javascript">


</script>
</html>

RPG/game/templates/game/charChreate.html
<!DOCTYPE html>
<html lang="en">
{% extends 'game/base.html' %}
    {% block gameContent %}
        <form method="post" action="">
            {{charMaker_form.as_p}}
            {% csrf_token %}
            <button type="submit" >Erschaffen</button>
        </form>
    {% endblock %}

RPG/game/templates/game/charcter.html
<!DOCTYPE html>
<html lang="en">
{% extends 'game/base.html' %}
    {% block gameContent %}
        <a href="{%url 'log:logout'%}">Logout</a>
        <br>
        {% if request.user.is_authenticated %}
            {% for i in chars %}
                {% if i.user == request.user %}
                    <h3>Dein Char:</h3>
                    <p>Name:            {{ i.charName}}</p>
                    <p>Klasse:          {{ i.charClasse}}</p>
                    {% if i.charClasse == 'Krieger'%}
                        <img src="/static/kleinerRitter.png" />
                    {% elif i.charClasse == 'Magier'%}
                        <img src="/static/kleinerMagier.png" />
                    {% endif%}
                    <p>ATK:             {{ i.charATK}}</p>
                    <p>DEF:             {{ i.charDEF}}</p>
                    <p>MAN:             {{ i.charMAN}}</p>
                    <p>EP:              {{ i.charEP}}</p>
                    <p>Level:           {{ i.charLevel}}</p>
                    <p>vernichtet:      {{ i.besigtegegner}}</p>
                    <br>
                    <a href="{%url 'game:kampf'%}">Kampf</a>
                {% else %}
                    <a href="{%url 'game:charChreate'%}">CahrMake</a>
                {% endif %}
            {% empty %}  <!-- wenn posts lehr ist -->
                {% if user == request.user %}
                    <p>Du hast noch kein Char</p>
                    <a href="{%url 'game:charChreate'%}"> CahrMake</a>
                {%else%}
                    <p> Der User {{ user.username }} hatt noch keine Einträge</p>
                {% endif %}
            {% endfor %}
        {%else%}
            <a href="{%url 'log:login'%}">Login</a>
            <a href="{%url 'log:register'%}">Account anlegen</a>

        {% endif %}
    {% endblock %}
</html>

RPG/game/templates/game/kampf.html
<!DOCTYPE html>
<html lang="en">
{% extends 'game/base.html' %}

    {% block gameContent %}
            {% if request.user.is_authenticated %}
                {% for i in chars %}
                    {% if i.user == request.user %}
                        <input type ="button" class = "button" id ="start" value="Start" onclick="startKampf({{ankreifer.leben}},{{ gegner.leben}})">

                            <div id = "Char" style="visibility: hidden">
                            <h1>Du</h1>
                            <p>Name:            {{ i.charName}}</p>
                            <p>KLasse:          {{ i.charClasse}}</p>
                            {% if i.charClasse == 'Krieger'%}
                                <img src="/static/kleinerRitter.png" />
                            {% elif i.charClasse == 'Magier'%}
                                <img src="/static/kleinerMagier.png" />
                             {% endif%}
                            <p id = "leben"> </p>
                          </div>

                            <br>

                            <div id = "Gegner" style="visibility: hidden">
                            <h1>Gegner</h1>
                            {% if gegner.name == 'Der grinsende Tod'%}
                                <img src="/static/Der_grinsende_Tod.jpg" />
                            {% elif gegner.name == 'Elektroball'%}
                                <img src="/static/Elektroball.jpg" />
                            {% elif gegner.name == 'Jack' %}
                                <img src="/static/Jack.jpg" />
                            {% endif%}
                            <p>Name:           {{gegner.name}}</p>
                            <p id = "leben2"></p>
                          </div>

                            <br>

                    {% else %}
                        <a href="{%url 'game:charChreate'%}">CahrMake</a>
                    {% endif %}
                {% endfor %}
                {% endif %}
            <div id = "Atacken" style="visibility: hidden">
            <p>___________________________</p>
            <p>Angriffe:</p>
            <input type="button" class = "button" id="angrif1" value="Schwert"  onclick="angriffSwerthib({{ankreifer.atk}},{{ankreifer.level}},{{gegner.dEF}});Kampf()">
            <input type="button" class = "button" id="angrif2" value="Magieball" onclick="angriffMagieball({{ankreifer.man}},{{ankreifer.level}},{{gegner.dEF}});Kampf()">
            <p>___________________________</p>
            <input type="button" class = "button" id="gegnerk" value="Angriff Gegner" disabled="disabled"  onclick="gegnerk({{gegner.atk}}, {{gegner.man}}, {{ankreifer.level}},{{ankreifer.dEF}});Kampf()">
            </div>
            <p id="ausgang"></p>
            <a href ="{%url 'game:sieg'%}"  id="Sieg" name ="Sieg"  style="visibility: hidden">Weiter</a>
            <a href ="{%url 'game:niederlage'%}" id = "Niederlage" name ='Niedelage' style="visibility: hidden">Weiter</a>

{% csrf_token %}
    {% endblock %}


</html>